[package]
name = "ormx"
version = "0.3.0"
authors = ["Moritz Bischof"]
edition = "2018"
license = "MIT"

[features]
mysql = ["sqlx/mysql", "ormx-macros/mysql"]
sqlite = ["sqlx/sqlite", "ormx-macros/sqlite"]
postgres = ["sqlx/postgres", "ormx-macros/postgres"]

[dependencies]
ormx-macros = { path = "../ormx-macros" }
futures = "0.3"

[dependencies.sqlx]
version = "0.4.0-beta.1"
default-features = false